$ErrorActionPreference = "Stop"
$langDir = "E:\Programieren\Projekte\Ultimate Apple Mod\forge\src\main\resources\assets\ultimate_apple_mod\lang\"

$enText = Get-Content ($langDir + "en_us.json") -Raw -Encoding UTF8
$enJson = $enText | ConvertFrom-Json
$orderedKeys = [System.Collections.Generic.List[string]]::new()
foreach ($line in ($enText -split "`n")) {
    if ($line -match '"([^"]+)"\s*:') { $orderedKeys.Add($Matches[1]) }
}
$enHT = @{}
foreach ($p in $enJson.PSObject.Properties) { $enHT[$p.Name] = $p.Value }

function ReadLang([string]$file) {
    if (-not (Test-Path $file)) { return @{} }
    $ht = @{}
    try {
        $j = (Get-Content $file -Raw -Encoding UTF8) | ConvertFrom-Json
        foreach ($p in $j.PSObject.Properties) { $ht[$p.Name] = $p.Value }
    } catch {}
    return $ht
}

function WriteLang([string]$name, [hashtable]$overrides) {
    $sb = [System.Text.StringBuilder]::new()
    $null = $sb.AppendLine("{")
    $count = 0
    foreach ($key in $orderedKeys) {
        $count++
        $val = if ($overrides.ContainsKey($key)) { $overrides[$key] } else { $enHT[$key] }
        $escaped = $val -replace '\\','\\' -replace '"','\"'
        $comma = if ($count -lt $orderedKeys.Count) { "," } else { "" }
        $null = $sb.AppendLine("  `"$key`": `"$escaped`"$comma")
    }
    $null = $sb.AppendLine("}")
    $path = $langDir + $name + ".json"
    [System.IO.File]::WriteAllText($path, $sb.ToString(), [System.Text.Encoding]::UTF8)
    Write-Host ("  Wrote " + $name + ".json")
}

# German variants: copy fixed de_de
$deDE = ReadLang ($langDir + "de_de.json")
WriteLang "de_at" $deDE
WriteLang "de_ch" $deDE

# English variants: copy en_us
foreach ($v in @("en_au","en_ca","en_gb","en_nz")) { WriteLang $v @{} }

# French
$fr = @{
    "item.ultimate_apple_mod.diamond_apple"              = "Pomme de diamant"
    "item.ultimate_apple_mod.iron_apple"                 = "Pomme de fer"
    "item.ultimate_apple_mod.rotten_apple"               = "Pomme pourrie"
    "itemGroup.ultimate_apple_mod.ultimate_tab"          = "Ultimate Apple Mod"
    "item.ultimate_apple_mod.baked_apple"                = "Pomme cuite"
    "item.ultimate_apple_mod.roasted_apple"              = "Pomme rotie"
    "item.ultimate_apple_mod.burnt_apple"                = "Pomme brulee"
    "item.ultimate_apple_mod.emerald_apple"              = "Pomme d'emeraude"
    "item.ultimate_apple_mod.netherite_apple"            = "Pomme en netherite"
    "item.ultimate_apple_mod.lapislazuli_apple"          = "Pomme de lapis-lazuli"
    "item.ultimate_apple_mod.redstone_apple"             = "Pomme de redstone"
    "item.ultimate_apple_mod.pear_apple"                 = "Poire"
    "item.ultimate_apple_mod.blaze_apple"                = "Pomme de blaze"
    "item.ultimate_apple_mod.ender_pearl_apple"          = "Pomme de perle de l'Ender"
    "item.ultimate_apple_mod.copper_apple"               = "Pomme de cuivre"
    "item.ultimate_apple_mod.moon_apple"                 = "Pomme lunaire"
    "item.ultimate_apple_mod.orchard_apple"              = "Pomme du verger"
    "item.ultimate_apple_mod.echo_apple"                 = "Pomme echo"
    "item.ultimate_apple_mod.rewind_apple"               = "Pomme retour"
    "item.ultimate_apple_mod.apple_bomb"                 = "Bombe-pomme"
    "item.ultimate_apple_mod.tnt_apple"                  = "Pomme TNT"
    "tooltip.ultimate_apple_mod.tnt_apple.line1"         = "§6Lancer pour creer une explosion TNT."
    "tooltip.ultimate_apple_mod.tnt_apple.line2"         = "§7Mixer avec une pomme pour des effets explosifs !"
    "item.ultimate_apple_mod.wither_apple"               = "Pomme du Wither"
    "item.ultimate_apple_mod.honey_apple"                = "Pomme au miel"
    "item.ultimate_apple_mod.dragon_apple"               = "Pomme du dragon"
    "item.ultimate_apple_mod.nether_star_apple"          = "Pomme de l'etoile du Nether"
    "item.ultimate_apple_mod.dirt_apple"                 = "Pomme de terre"
    "item.ultimate_apple_mod.totem_apple"                = "Pomme totem"
    "item.ultimate_apple_mod.quantum_apple"              = "Pomme quantique"
    "item.ultimate_apple_mod.void_apple"                 = "Pomme du vide"
    "item.ultimate_apple_mod.time_freeze_apple"          = "Pomme gel du temps"
    "item.ultimate_apple_mod.longevity_apple"            = "Pomme de longevite"
    "item.ultimate_apple_mod.prism_apple"                = "Pomme prismatique"
    "item.ultimate_apple_mod.banana"                     = "Banane"
    "item.ultimate_apple_mod.cup"                        = "Verre"
    "item.ultimate_apple_mod.shake"                      = "Milk-shake"
    "block.ultimate_apple_mod.mixer"                     = "Mixeur"
    "container.ultimate_apple_mod.mixer"                 = "Mixeur"
    "gui.ultimate_apple_mod.mixer.cup"                   = "Verre"
    "gui.ultimate_apple_mod.mixer.ingredients"           = "Ingredients"
    "effect.ultimate_apple_mod.curse_of_rotten"          = "Malediction de la pourriture"
    "effect.ultimate_apple_mod.moon_gravity"             = "Gravite lunaire"
    "effect.ultimate_apple_mod.glitch"                   = "Glitch"
    "effect.ultimate_apple_mod.lifesteal"                = "Vol de vie"
    "effect.ultimate_apple_mod.totem_protection"         = "Protection du totem"
    "effect.ultimate_apple_mod.time_freeze"              = "Gel du temps"
    "key.ultimate_apple_mod.fire_dragon_breath"          = "Lancer le souffle du dragon"
    "key.categories.ultimate_apple_mod"                  = "Ultimate Apple Mod"
    "message.ultimate_apple_mod.lifesteal_heal"          = "§c+1 coeur Vol de vie"
    "message.ultimate_apple_mod.nothing_can_grow"        = "Rien ne peut pousser ici."
    "message.ultimate_apple_mod.echo_set"                = "Point de retour defini !"
    "message.ultimate_apple_mod.echo_return"             = "Echo !"
    "message.ultimate_apple_mod.echo_wrong_dim"          = "Impossible de teleporter entre dimensions."
    "message.ultimate_apple_mod.rewind"                  = "§bRetour en arriere !"
    "message.ultimate_apple_mod.rewind_no_history"       = "§7Pas encore d'historique..."
    "message.ultimate_apple_mod.dragon_breath_remaining" = "§c%s charge(s) de souffle restante(s)."
    "message.ultimate_apple_mod.wither_curse_applied"    = "§5Malediction du Wither appliquee !"
    "message.ultimate_apple_mod.dragon_charges_added"    = "§6+%s charge(s) de souffle via Shake !"
    "message.ultimate_apple_mod.totem_apple_triggered"   = "§6La Pomme totem t'a sauve de la mort !"
    "tooltip.ultimate_apple_mod.ender_pearl_apple.line1" = "§6Teleportation dans la direction du regard."
    "tooltip.ultimate_apple_mod.ender_pearl_apple.line2" = "§7Jusqu'a 256 blocs avec le pouvoir des Endermens."
    "tooltip.ultimate_apple_mod.echo_apple.line1"        = "§6Premiere utilisation : definit un point de retour."
    "tooltip.ultimate_apple_mod.echo_apple.line2"        = "§7Deuxieme utilisation : teleportation vers ce point."
    "tooltip.ultimate_apple_mod.rewind_apple.line1"      = "§6Te teleporte a ta position il y a 5 secondes."
    "tooltip.ultimate_apple_mod.rewind_apple.line2"      = "§7Position enregistree chaque seconde. Prudence !"
    "tooltip.ultimate_apple_mod.wither_apple.line1"      = "§6Maudit les mobs proches avec Wither II et donne Vol de vie."
    "tooltip.ultimate_apple_mod.wither_apple.line2"      = "§7Chaque kill soigne 1 coeur. Effet dure 1 minute."
    "tooltip.ultimate_apple_mod.dragon_apple.line1"      = "§6Clic gauche pour lancer le souffle du dragon (1 charge)."
    "tooltip.ultimate_apple_mod.dragon_apple.line2"      = "§7Manger charge des cartes. Ne tire pas pendant un combat."
    "tooltip.ultimate_apple_mod.honey_apple.line1"       = "§6Soigne instantanement tous les effets actifs."
    "tooltip.ultimate_apple_mod.honey_apple.line2"       = "§7Te ralentit brievement apres."
    "tooltip.ultimate_apple_mod.nether_star_apple.line1" = "§62 secondes d'invincibilite absolue."
    "tooltip.ultimate_apple_mod.nether_star_apple.line2" = "§7A manipuler avec precaution."
    "tooltip.ultimate_apple_mod.apple_bomb.line1"        = "§6Lancer pour donner des effets aux entites proches."
    "tooltip.ultimate_apple_mod.shake.effects"           = "§6Effets :"
    "tooltip.ultimate_apple_mod.shake.no_effects"        = "§7Aucun effet stocke."
    "advancements.ultimate_apple_mod.root.title"         = "Ultimate Apple Mod"
    "advancements.ultimate_apple_mod.root.description"   = "Decouvre le monde des pommes magiques."
    "advancements.ultimate_apple_mod.apple.title"        = "Une pomme par jour..."
    "advancements.ultimate_apple_mod.apple.description"  = "Mange une pomme ordinaire."
    "advancements.ultimate_apple_mod.baked_apple.title"  = "Fraichement cuite"
    "advancements.ultimate_apple_mod.baked_apple.description" = "Mange une Pomme cuite."
    "advancements.ultimate_apple_mod.roasted_apple.title" = "Delice grille"
    "advancements.ultimate_apple_mod.roasted_apple.description" = "Mange une Pomme rotie."
    "advancements.ultimate_apple_mod.pear_apple.title"   = "Ce n'est pas une pomme"
    "advancements.ultimate_apple_mod.pear_apple.description" = "Mange une Poire."
    "advancements.ultimate_apple_mod.banana.title"       = "Pomme longue"
    "advancements.ultimate_apple_mod.banana.description" = "Mange une Banane."
    "advancements.ultimate_apple_mod.rotten_apple.title" = "Mieux que rien ?"
    "advancements.ultimate_apple_mod.rotten_apple.description" = "Mange une Pomme pourrie. Bonne chance."
    "advancements.ultimate_apple_mod.burnt_apple.title"  = "Bien cuit"
    "advancements.ultimate_apple_mod.burnt_apple.description" = "Mange une Pomme brulee — ca a un gout de regret."
    "advancements.ultimate_apple_mod.dirt_apple.title"   = "Sors un peu"
    "advancements.ultimate_apple_mod.dirt_apple.description" = "Mange une Pomme de terre. Mais pourquoi ?"
    "advancements.ultimate_apple_mod.blaze_apple.title"  = "Encas ignifuge"
    "advancements.ultimate_apple_mod.blaze_apple.description" = "Mange une Pomme de blaze."
    "advancements.ultimate_apple_mod.golden_apple.title" = "Tout ce qui brille..."
    "advancements.ultimate_apple_mod.golden_apple.description" = "Mange une Pomme en or."
    "advancements.ultimate_apple_mod.iron_apple.title"   = "Constitution de fer"
    "advancements.ultimate_apple_mod.iron_apple.description" = "Mange une Pomme de fer."
    "advancements.ultimate_apple_mod.copper_apple.title" = "Forge solide"
    "advancements.ultimate_apple_mod.copper_apple.description" = "Mange une Pomme de cuivre."
    "advancements.ultimate_apple_mod.redstone_apple.title" = "Charge maximale"
    "advancements.ultimate_apple_mod.redstone_apple.description" = "Mange une Pomme de redstone."
    "advancements.ultimate_apple_mod.lapislazuli_apple.title" = "L'Enchanteur"
    "advancements.ultimate_apple_mod.lapislazuli_apple.description" = "Mange une Pomme de lapis-lazuli."
    "advancements.ultimate_apple_mod.emerald_apple.title" = "La fortune sourit aux courageux"
    "advancements.ultimate_apple_mod.emerald_apple.description" = "Mange une Pomme d'emeraude."
    "advancements.ultimate_apple_mod.moon_apple.title"   = "La gravite ? Connais pas."
    "advancements.ultimate_apple_mod.moon_apple.description" = "Mange une Pomme lunaire et saute vers les cieux."
    "advancements.ultimate_apple_mod.ender_pearl_apple.title" = "Encas dimensionnel"
    "advancements.ultimate_apple_mod.ender_pearl_apple.description" = "Mange une Pomme de perle de l'Ender."
    "advancements.ultimate_apple_mod.honey_apple.title"  = "Cure douce"
    "advancements.ultimate_apple_mod.honey_apple.description" = "Mange une Pomme au miel et nettoie tes effets."
    "advancements.ultimate_apple_mod.wither_apple.title" = "Force vitale"
    "advancements.ultimate_apple_mod.wither_apple.description" = "Mange une Pomme du Wither et obtiens le Vol de vie."
    "advancements.ultimate_apple_mod.echo_apple.title"   = "Echo du vide"
    "advancements.ultimate_apple_mod.echo_apple.description" = "Mange une Pomme echo et marque ton retour."
    "advancements.ultimate_apple_mod.rewind_apple.title" = "Remonter le temps"
    "advancements.ultimate_apple_mod.rewind_apple.description" = "Mange une Pomme retour."
    "advancements.ultimate_apple_mod.orchard_apple.title" = "Le verger appelle"
    "advancements.ultimate_apple_mod.orchard_apple.description" = "Mange une Pomme du verger et invoque une foret."
    "advancements.ultimate_apple_mod.void_apple.title"   = "Surfeur du ciel"
    "advancements.ultimate_apple_mod.void_apple.description" = "Mange une Pomme du vide et envole-toi."
    "advancements.ultimate_apple_mod.time_freeze_apple.title" = "L'eclair"
    "advancements.ultimate_apple_mod.time_freeze_apple.description" = "Mange une Pomme gel du temps. Le monde s'arrete, pas toi."
    "advancements.ultimate_apple_mod.longevity_apple.title" = "Vivre pour toujours"
    "advancements.ultimate_apple_mod.longevity_apple.description" = "Mange une Pomme de longevite."
    "advancements.ultimate_apple_mod.enchanted_golden_apple.title" = "Fruit interdit"
    "advancements.ultimate_apple_mod.enchanted_golden_apple.description" = "Mange une Pomme en or enchantee."
    "advancements.ultimate_apple_mod.diamond_apple.title" = "Appetit adamantin"
    "advancements.ultimate_apple_mod.diamond_apple.description" = "Mange une Pomme de diamant."
    "advancements.ultimate_apple_mod.netherite_apple.title" = "Invincible"
    "advancements.ultimate_apple_mod.netherite_apple.description" = "Mange une Pomme en netherite. Tu es inarretable."
    "advancements.ultimate_apple_mod.dragon_apple.title" = "Festin du tueur de dragon"
    "advancements.ultimate_apple_mod.dragon_apple.description" = "Mange une Pomme du dragon et incarne le dragon de l'End."
    "advancements.ultimate_apple_mod.nether_star_apple.title" = "Puissance des etoiles"
    "advancements.ultimate_apple_mod.nether_star_apple.description" = "Mange une Pomme de l'etoile du Nether. 2 secondes d'invincibilite."
    "advancements.ultimate_apple_mod.totem_apple.title"  = "Tu ne peux pas me tuer"
    "advancements.ultimate_apple_mod.totem_apple.description" = "Mange une Pomme totem et trompe la mort."
    "advancements.ultimate_apple_mod.quantum_apple.title" = "Le casse-croute de Schrodinger"
    "advancements.ultimate_apple_mod.quantum_apple.description" = "Mange une Pomme quantique. Tu n'avais aucune idee."
    "advancements.ultimate_apple_mod.prism_apple.title"  = "Plongeur des grands fonds"
    "advancements.ultimate_apple_mod.prism_apple.description" = "Mange une Pomme prismatique et conquiers l'ocean."
    "advancements.ultimate_apple_mod.mix_first_shake.title" = "Le Mixologue"
    "advancements.ultimate_apple_mod.mix_first_shake.description" = "Mixe deux pommes dans le Mixeur pour ton premier Shake."
    "advancements.ultimate_apple_mod.drink_first_shake.title" = "Sante !"
    "advancements.ultimate_apple_mod.drink_first_shake.description" = "Bois un Shake et gote la puissance de deux pommes."
    "advancements.ultimate_apple_mod.eat_all_apples.title" = "Connaisseur de pommes"
    "advancements.ultimate_apple_mod.eat_all_apples.description" = "Mange chaque pomme du mod. Un vrai amoureux des pommes."
}
WriteLang "fr_fr" $fr
WriteLang "fr_ca" $fr

# Spanish
$es = @{
    "item.ultimate_apple_mod.diamond_apple"              = "Manzana de diamante"
    "item.ultimate_apple_mod.iron_apple"                 = "Manzana de hierro"
    "item.ultimate_apple_mod.rotten_apple"               = "Manzana podrida"
    "itemGroup.ultimate_apple_mod.ultimate_tab"          = "Ultimate Apple Mod"
    "item.ultimate_apple_mod.baked_apple"                = "Manzana horneada"
    "item.ultimate_apple_mod.roasted_apple"              = "Manzana asada"
    "item.ultimate_apple_mod.burnt_apple"                = "Manzana quemada"
    "item.ultimate_apple_mod.emerald_apple"              = "Manzana de esmeralda"
    "item.ultimate_apple_mod.netherite_apple"            = "Manzana de netherita"
    "item.ultimate_apple_mod.lapislazuli_apple"          = "Manzana de lapislazuli"
    "item.ultimate_apple_mod.redstone_apple"             = "Manzana de redstone"
    "item.ultimate_apple_mod.pear_apple"                 = "Pera"
    "item.ultimate_apple_mod.blaze_apple"                = "Manzana llameante"
    "item.ultimate_apple_mod.ender_pearl_apple"          = "Manzana de perla de Ender"
    "item.ultimate_apple_mod.copper_apple"               = "Manzana de cobre"
    "item.ultimate_apple_mod.moon_apple"                 = "Manzana lunar"
    "item.ultimate_apple_mod.orchard_apple"              = "Manzana del huerto"
    "item.ultimate_apple_mod.echo_apple"                 = "Manzana eco"
    "item.ultimate_apple_mod.rewind_apple"               = "Manzana rebobinadora"
    "item.ultimate_apple_mod.apple_bomb"                 = "Bomba manzana"
    "item.ultimate_apple_mod.tnt_apple"                  = "Manzana TNT"
    "tooltip.ultimate_apple_mod.tnt_apple.line1"         = "§6Lanzar para crear una explosion TNT."
    "tooltip.ultimate_apple_mod.tnt_apple.line2"         = "§7Mezclar con cualquier manzana para efectos explosivos!"
    "item.ultimate_apple_mod.wither_apple"               = "Manzana marchita"
    "item.ultimate_apple_mod.honey_apple"                = "Manzana de miel"
    "item.ultimate_apple_mod.dragon_apple"               = "Manzana del dragon"
    "item.ultimate_apple_mod.nether_star_apple"          = "Manzana de la estrella del Nether"
    "item.ultimate_apple_mod.dirt_apple"                 = "Manzana de tierra"
    "item.ultimate_apple_mod.totem_apple"                = "Manzana totem"
    "item.ultimate_apple_mod.quantum_apple"              = "Manzana cuantica"
    "item.ultimate_apple_mod.void_apple"                 = "Manzana del vacio"
    "item.ultimate_apple_mod.time_freeze_apple"          = "Manzana congeladora"
    "item.ultimate_apple_mod.longevity_apple"            = "Manzana de longevidad"
    "item.ultimate_apple_mod.prism_apple"                = "Manzana prisma"
    "item.ultimate_apple_mod.banana"                     = "Platano"
    "item.ultimate_apple_mod.cup"                        = "Vaso"
    "item.ultimate_apple_mod.shake"                      = "Batido"
    "block.ultimate_apple_mod.mixer"                     = "Mezclador"
    "container.ultimate_apple_mod.mixer"                 = "Mezclador"
    "gui.ultimate_apple_mod.mixer.cup"                   = "Vaso"
    "gui.ultimate_apple_mod.mixer.ingredients"           = "Ingredientes"
    "effect.ultimate_apple_mod.curse_of_rotten"          = "Maldicion de la podredumbre"
    "effect.ultimate_apple_mod.moon_gravity"             = "Gravedad lunar"
    "effect.ultimate_apple_mod.glitch"                   = "Glitch"
    "effect.ultimate_apple_mod.lifesteal"                = "Robo de vida"
    "effect.ultimate_apple_mod.totem_protection"         = "Proteccion del totem"
    "effect.ultimate_apple_mod.time_freeze"              = "Congelacion del tiempo"
    "key.ultimate_apple_mod.fire_dragon_breath"          = "Lanzar aliento de dragon"
    "key.categories.ultimate_apple_mod"                  = "Ultimate Apple Mod"
    "message.ultimate_apple_mod.lifesteal_heal"          = "§c+1 corazon Robo de vida"
    "message.ultimate_apple_mod.nothing_can_grow"        = "Nada puede crecer aqui."
    "message.ultimate_apple_mod.echo_set"                = "Punto de retorno establecido!"
    "message.ultimate_apple_mod.echo_return"             = "Eco!"
    "message.ultimate_apple_mod.echo_wrong_dim"          = "No se puede teleportar entre dimensiones."
    "message.ultimate_apple_mod.rewind"                  = "§bRebobinado! Enviado 5 segundos atras."
    "message.ultimate_apple_mod.rewind_no_history"       = "§7Sin historial aun..."
    "message.ultimate_apple_mod.dragon_breath_remaining" = "§c%s carga(s) de aliento de dragon restante(s)."
    "message.ultimate_apple_mod.wither_curse_applied"    = "§5Maldicion del Wither aplicada a mobs cercanos!"
    "message.ultimate_apple_mod.dragon_charges_added"    = "§6+%s carga(s) de aliento via Shake!"
    "message.ultimate_apple_mod.totem_apple_triggered"   = "§6La Manzana totem te ha salvado de la muerte!"
    "tooltip.ultimate_apple_mod.ender_pearl_apple.line1" = "§6Teleportacion en la linea de vision."
    "tooltip.ultimate_apple_mod.ender_pearl_apple.line2" = "§7Hasta 256 bloques con el poder de los Endermen."
    "tooltip.ultimate_apple_mod.echo_apple.line1"        = "§6Primer uso: establece un punto de retorno."
    "tooltip.ultimate_apple_mod.echo_apple.line2"        = "§7Segundo uso: te teleporta de vuelta."
    "tooltip.ultimate_apple_mod.rewind_apple.line1"      = "§6Te teleporta a tu posicion hace 5 segundos."
    "tooltip.ultimate_apple_mod.rewind_apple.line2"      = "§7Posicion registrada cada segundo. Cuidado!"
    "tooltip.ultimate_apple_mod.wither_apple.line1"      = "§6Maldice mobs cercanos con Wither II y da Robo de vida."
    "tooltip.ultimate_apple_mod.wither_apple.line2"      = "§7Cada kill cura 1 corazon. Efecto dura 1 minuto."
    "tooltip.ultimate_apple_mod.dragon_apple.line1"      = "§6Clic izquierdo para lanzar aliento (1 carga)."
    "tooltip.ultimate_apple_mod.dragon_apple.line2"      = "§7Comer carga cargas. No dispara durante combate."
    "tooltip.ultimate_apple_mod.honey_apple.line1"       = "§6Cura instantaneamente todos los efectos activos."
    "tooltip.ultimate_apple_mod.honey_apple.line2"       = "§7Te ralentiza brevemente despues."
    "tooltip.ultimate_apple_mod.nether_star_apple.line1" = "§62 segundos de invencibilidad absoluta."
    "tooltip.ultimate_apple_mod.nether_star_apple.line2" = "§7Manejar con precaucion."
    "tooltip.ultimate_apple_mod.apple_bomb.line1"        = "§6Lanzar para dar efectos a entidades cercanas."
    "tooltip.ultimate_apple_mod.shake.effects"           = "§6Efectos:"
    "tooltip.ultimate_apple_mod.shake.no_effects"        = "§7Sin efectos almacenados."
    "advancements.ultimate_apple_mod.root.title"         = "Ultimate Apple Mod"
    "advancements.ultimate_apple_mod.root.description"   = "Descubre el mundo de las manzanas magicas."
    "advancements.ultimate_apple_mod.apple.title"        = "Una manzana al dia..."
    "advancements.ultimate_apple_mod.apple.description"  = "Come una manzana normal."
    "advancements.ultimate_apple_mod.baked_apple.title"  = "Recien horneada"
    "advancements.ultimate_apple_mod.baked_apple.description" = "Come una Manzana horneada."
    "advancements.ultimate_apple_mod.roasted_apple.title" = "Deleite asado"
    "advancements.ultimate_apple_mod.roasted_apple.description" = "Come una Manzana asada."
    "advancements.ultimate_apple_mod.pear_apple.title"   = "En realidad no es una manzana"
    "advancements.ultimate_apple_mod.pear_apple.description" = "Come una Pera."
    "advancements.ultimate_apple_mod.banana.title"       = "Manzana larga"
    "advancements.ultimate_apple_mod.banana.description" = "Come un Platano."
    "advancements.ultimate_apple_mod.rotten_apple.title" = "Mejor que nada?"
    "advancements.ultimate_apple_mod.rotten_apple.description" = "Come una Manzana podrida. Buena suerte."
    "advancements.ultimate_apple_mod.burnt_apple.title"  = "Bien hecha"
    "advancements.ultimate_apple_mod.burnt_apple.description" = "Come una Manzana quemada, sabe a arrepentimiento."
    "advancements.ultimate_apple_mod.dirt_apple.title"   = "Sal un poco"
    "advancements.ultimate_apple_mod.dirt_apple.description" = "Come una Manzana de tierra. Por que lo harias."
    "advancements.ultimate_apple_mod.blaze_apple.title"  = "Aperitivo ignifugo"
    "advancements.ultimate_apple_mod.blaze_apple.description" = "Come una Manzana llameante."
    "advancements.ultimate_apple_mod.golden_apple.title" = "Todo lo que brilla..."
    "advancements.ultimate_apple_mod.golden_apple.description" = "Come una Manzana de oro."
    "advancements.ultimate_apple_mod.iron_apple.title"   = "Constitucion de hierro"
    "advancements.ultimate_apple_mod.iron_apple.description" = "Come una Manzana de hierro."
    "advancements.ultimate_apple_mod.copper_apple.title" = "Forjado fuerte"
    "advancements.ultimate_apple_mod.copper_apple.description" = "Come una Manzana de cobre."
    "advancements.ultimate_apple_mod.redstone_apple.title" = "Cargado al maximo"
    "advancements.ultimate_apple_mod.redstone_apple.description" = "Come una Manzana de redstone."
    "advancements.ultimate_apple_mod.lapislazuli_apple.title" = "El Encantador"
    "advancements.ultimate_apple_mod.lapislazuli_apple.description" = "Come una Manzana de lapislazuli."
    "advancements.ultimate_apple_mod.emerald_apple.title" = "La fortuna favorece al valiente"
    "advancements.ultimate_apple_mod.emerald_apple.description" = "Come una Manzana de esmeralda."
    "advancements.ultimate_apple_mod.moon_apple.title"   = "Gravedad? No la conozco."
    "advancements.ultimate_apple_mod.moon_apple.description" = "Come una Manzana lunar y salta hasta el cielo."
    "advancements.ultimate_apple_mod.ender_pearl_apple.title" = "Aperitivo dimensional"
    "advancements.ultimate_apple_mod.ender_pearl_apple.description" = "Come una Manzana de perla de Ender."
    "advancements.ultimate_apple_mod.honey_apple.title"  = "Desintoxicacion dulce"
    "advancements.ultimate_apple_mod.honey_apple.description" = "Come una Manzana de miel y limpia tus efectos."
    "advancements.ultimate_apple_mod.wither_apple.title" = "Fuerza vital"
    "advancements.ultimate_apple_mod.wither_apple.description" = "Come una Manzana marchita y obtiene Robo de vida."
    "advancements.ultimate_apple_mod.echo_apple.title"   = "Eco del vacio"
    "advancements.ultimate_apple_mod.echo_apple.description" = "Come una Manzana eco y marca tu retorno."
    "advancements.ultimate_apple_mod.rewind_apple.title" = "Retroceder el tiempo"
    "advancements.ultimate_apple_mod.rewind_apple.description" = "Come una Manzana rebobinadora."
    "advancements.ultimate_apple_mod.orchard_apple.title" = "El huerto llama"
    "advancements.ultimate_apple_mod.orchard_apple.description" = "Come una Manzana del huerto e invoca un bosque."
    "advancements.ultimate_apple_mod.void_apple.title"   = "Surfista del cielo"
    "advancements.ultimate_apple_mod.void_apple.description" = "Come una Manzana del vacio y lanzate al cielo."
    "advancements.ultimate_apple_mod.time_freeze_apple.title" = "El Relampago"
    "advancements.ultimate_apple_mod.time_freeze_apple.description" = "Come una Manzana congeladora. El mundo se detiene, tu no."
    "advancements.ultimate_apple_mod.longevity_apple.title" = "Vivir para siempre"
    "advancements.ultimate_apple_mod.longevity_apple.description" = "Come una Manzana de longevidad."
    "advancements.ultimate_apple_mod.enchanted_golden_apple.title" = "Fruta prohibida"
    "advancements.ultimate_apple_mod.enchanted_golden_apple.description" = "Come una Manzana de oro encantada."
    "advancements.ultimate_apple_mod.diamond_apple.title" = "Apetito de diamante"
    "advancements.ultimate_apple_mod.diamond_apple.description" = "Come una Manzana de diamante."
    "advancements.ultimate_apple_mod.netherite_apple.title" = "Invencible"
    "advancements.ultimate_apple_mod.netherite_apple.description" = "Come una Manzana de netherita. Eres imparable."
    "advancements.ultimate_apple_mod.dragon_apple.title" = "Festin del matadragones"
    "advancements.ultimate_apple_mod.dragon_apple.description" = "Come una Manzana del dragon y domina al Enderdragon."
    "advancements.ultimate_apple_mod.nether_star_apple.title" = "Poder estelar"
    "advancements.ultimate_apple_mod.nether_star_apple.description" = "Come una Manzana de la estrella del Nether."
    "advancements.ultimate_apple_mod.totem_apple.title"  = "No puedes matarme"
    "advancements.ultimate_apple_mod.totem_apple.description" = "Come una Manzana totem y engana a la muerte."
    "advancements.ultimate_apple_mod.quantum_apple.title" = "El aperitivo de Schrodinger"
    "advancements.ultimate_apple_mod.quantum_apple.description" = "Come una Manzana cuantica. No tenias ni idea."
    "advancements.ultimate_apple_mod.prism_apple.title"  = "Buzo de las profundidades"
    "advancements.ultimate_apple_mod.prism_apple.description" = "Come una Manzana prisma y conquista el oceano."
    "advancements.ultimate_apple_mod.mix_first_shake.title" = "El Mixologo"
    "advancements.ultimate_apple_mod.mix_first_shake.description" = "Mezcla dos manzanas en el Mezclador para tu primer Batido."
    "advancements.ultimate_apple_mod.drink_first_shake.title" = "Salud!"
    "advancements.ultimate_apple_mod.drink_first_shake.description" = "Bebe un Batido y saborea el poder de dos manzanas."
    "advancements.ultimate_apple_mod.eat_all_apples.title" = "Conocedor de manzanas"
    "advancements.ultimate_apple_mod.eat_all_apples.description" = "Come cada manzana del mod. Un verdadero amante de las manzanas."
}
foreach ($v in @("es_es","es_ar","es_cl","es_ec","es_mx","es_uy","es_ve")) { WriteLang $v $es }

# Portuguese
$pt = @{
    "item.ultimate_apple_mod.diamond_apple"              = "Maca de diamante"
    "item.ultimate_apple_mod.iron_apple"                 = "Maca de ferro"
    "item.ultimate_apple_mod.rotten_apple"               = "Maca podre"
    "itemGroup.ultimate_apple_mod.ultimate_tab"          = "Ultimate Apple Mod"
    "item.ultimate_apple_mod.baked_apple"                = "Maca assada"
    "item.ultimate_apple_mod.roasted_apple"              = "Maca tostada"
    "item.ultimate_apple_mod.burnt_apple"                = "Maca queimada"
    "item.ultimate_apple_mod.emerald_apple"              = "Maca de esmeralda"
    "item.ultimate_apple_mod.netherite_apple"            = "Maca de netherite"
    "item.ultimate_apple_mod.lapislazuli_apple"          = "Maca de lapis-lazuli"
    "item.ultimate_apple_mod.redstone_apple"             = "Maca de redstone"
    "item.ultimate_apple_mod.pear_apple"                 = "Pera"
    "item.ultimate_apple_mod.blaze_apple"                = "Maca do blaze"
    "item.ultimate_apple_mod.ender_pearl_apple"          = "Maca de perola do Ender"
    "item.ultimate_apple_mod.copper_apple"               = "Maca de cobre"
    "item.ultimate_apple_mod.moon_apple"                 = "Maca lunar"
    "item.ultimate_apple_mod.orchard_apple"              = "Maca do pomar"
    "item.ultimate_apple_mod.echo_apple"                 = "Maca eco"
    "item.ultimate_apple_mod.rewind_apple"               = "Maca retrocesso"
    "item.ultimate_apple_mod.apple_bomb"                 = "Bomba de maca"
    "item.ultimate_apple_mod.tnt_apple"                  = "Maca TNT"
    "tooltip.ultimate_apple_mod.tnt_apple.line1"         = "§6Jogar para criar uma explosao TNT."
    "tooltip.ultimate_apple_mod.tnt_apple.line2"         = "§7Misturar com qualquer maca para efeitos explosivos!"
    "item.ultimate_apple_mod.wither_apple"               = "Maca do Wither"
    "item.ultimate_apple_mod.honey_apple"                = "Maca de mel"
    "item.ultimate_apple_mod.dragon_apple"               = "Maca do dragao"
    "item.ultimate_apple_mod.nether_star_apple"          = "Maca da estrela do Nether"
    "item.ultimate_apple_mod.dirt_apple"                 = "Maca de terra"
    "item.ultimate_apple_mod.totem_apple"                = "Maca totem"
    "item.ultimate_apple_mod.quantum_apple"              = "Maca quantica"
    "item.ultimate_apple_mod.void_apple"                 = "Maca do vazio"
    "item.ultimate_apple_mod.time_freeze_apple"          = "Maca congeladora"
    "item.ultimate_apple_mod.longevity_apple"            = "Maca da longevidade"
    "item.ultimate_apple_mod.prism_apple"                = "Maca prisma"
    "item.ultimate_apple_mod.banana"                     = "Banana"
    "item.ultimate_apple_mod.cup"                        = "Copo"
    "item.ultimate_apple_mod.shake"                      = "Milkshake"
    "block.ultimate_apple_mod.mixer"                     = "Misturador"
    "container.ultimate_apple_mod.mixer"                 = "Misturador"
    "gui.ultimate_apple_mod.mixer.cup"                   = "Copo"
    "gui.ultimate_apple_mod.mixer.ingredients"           = "Ingredientes"
    "effect.ultimate_apple_mod.curse_of_rotten"          = "Maldicao da podridao"
    "effect.ultimate_apple_mod.moon_gravity"             = "Gravidade lunar"
    "effect.ultimate_apple_mod.glitch"                   = "Glitch"
    "effect.ultimate_apple_mod.lifesteal"                = "Roubo de vida"
    "effect.ultimate_apple_mod.totem_protection"         = "Protecao do totem"
    "effect.ultimate_apple_mod.time_freeze"              = "Congelamento do tempo"
    "key.ultimate_apple_mod.fire_dragon_breath"          = "Disparar sopro do dragao"
    "key.categories.ultimate_apple_mod"                  = "Ultimate Apple Mod"
    "message.ultimate_apple_mod.lifesteal_heal"          = "§c+1 coracao Roubo de vida"
    "message.ultimate_apple_mod.nothing_can_grow"        = "Nada pode crescer aqui."
    "message.ultimate_apple_mod.echo_set"                = "Ponto de retorno definido!"
    "message.ultimate_apple_mod.echo_return"             = "Eco!"
    "message.ultimate_apple_mod.echo_wrong_dim"          = "Nao e possivel teleportar entre dimensoes."
    "message.ultimate_apple_mod.rewind"                  = "§bRetrocesso! Enviado 5 segundos ao passado."
    "message.ultimate_apple_mod.rewind_no_history"       = "§7Sem historico ainda..."
    "message.ultimate_apple_mod.dragon_breath_remaining" = "§c%s carga(s) de sopro do dragao restante(s)."
    "message.ultimate_apple_mod.wither_curse_applied"    = "§5Maldicao do Wither aplicada aos mobs proximos!"
    "message.ultimate_apple_mod.dragon_charges_added"    = "§6+%s carga(s) de sopro via Shake!"
    "message.ultimate_apple_mod.totem_apple_triggered"   = "§6A Maca totem te salvou da morte!"
    "tooltip.ultimate_apple_mod.ender_pearl_apple.line1" = "§6Teleporte na linha de visao."
    "tooltip.ultimate_apple_mod.ender_pearl_apple.line2" = "§7Ate 256 blocos com o poder dos Endermen."
    "tooltip.ultimate_apple_mod.echo_apple.line1"        = "§6Primeiro uso: define um ponto de retorno."
    "tooltip.ultimate_apple_mod.echo_apple.line2"        = "§7Segundo uso: teleporta de volta."
    "tooltip.ultimate_apple_mod.rewind_apple.line1"      = "§6Te teleporta para a posicao ha 5 segundos."
    "tooltip.ultimate_apple_mod.rewind_apple.line2"      = "§7Posicao rastreada por segundo. Cuidado!"
    "tooltip.ultimate_apple_mod.wither_apple.line1"      = "§6Amaldicoa mobs proximos com Wither II."
    "tooltip.ultimate_apple_mod.wither_apple.line2"      = "§7Cada kill cura 1 coracao. Efeito dura 1 minuto."
    "tooltip.ultimate_apple_mod.dragon_apple.line1"      = "§6Clique esquerdo para disparar o sopro (1 carga)."
    "tooltip.ultimate_apple_mod.dragon_apple.line2"      = "§7Comer carrega. Nao dispara durante combate."
    "tooltip.ultimate_apple_mod.honey_apple.line1"       = "§6Cura instantaneamente todos os efeitos ativos."
    "tooltip.ultimate_apple_mod.honey_apple.line2"       = "§7Te deixa brevemente mais lento depois."
    "tooltip.ultimate_apple_mod.nether_star_apple.line1" = "§62 segundos de invencibilidade absoluta."
    "tooltip.ultimate_apple_mod.nether_star_apple.line2" = "§7Manusear com cuidado."
    "tooltip.ultimate_apple_mod.apple_bomb.line1"        = "§6Jogar para dar efeitos a entidades proximas."
    "tooltip.ultimate_apple_mod.shake.effects"           = "§6Efeitos:"
    "tooltip.ultimate_apple_mod.shake.no_effects"        = "§7Nenhum efeito armazenado."
    "advancements.ultimate_apple_mod.root.title"         = "Ultimate Apple Mod"
    "advancements.ultimate_apple_mod.root.description"   = "Descubra o mundo das macas magicas."
    "advancements.ultimate_apple_mod.apple.title"        = "Uma maca por dia..."
    "advancements.ultimate_apple_mod.apple.description"  = "Coma uma maca normal."
    "advancements.ultimate_apple_mod.totem_apple.title"  = "Voce nao pode me matar"
    "advancements.ultimate_apple_mod.totem_apple.description" = "Coma uma Maca totem e engane a morte."
    "advancements.ultimate_apple_mod.quantum_apple.title" = "O lanche de Schrodinger"
    "advancements.ultimate_apple_mod.quantum_apple.description" = "Coma uma Maca quantica. Voce nao tinha ideia."
    "advancements.ultimate_apple_mod.mix_first_shake.title" = "O Mixologista"
    "advancements.ultimate_apple_mod.mix_first_shake.description" = "Misture duas macas no Misturador para seu primeiro Shake."
    "advancements.ultimate_apple_mod.drink_first_shake.title" = "Saude!"
    "advancements.ultimate_apple_mod.drink_first_shake.description" = "Beba um Shake e prove o poder de duas macas."
    "advancements.ultimate_apple_mod.eat_all_apples.title" = "Conhecedor de macas"
    "advancements.ultimate_apple_mod.eat_all_apples.description" = "Coma cada maca do mod. Um verdadeiro amante das macas."
}
WriteLang "pt_br" $pt
WriteLang "pt_pt" $pt

# All remaining: merge existing translations + English fallback
foreach ($name in @("ja_jp","ko_kr","ru_ru","zh_cn","zh_tw","ro_ro","tr_tr","da_dk","bar")) {
    $existing = ReadLang ($langDir + $name + ".json")
    $cleaned = @{}
    foreach ($k in $existing.Keys) {
        if ($enHT.ContainsKey($k)) { $cleaned[$k] = $existing[$k] }
    }
    WriteLang $name $cleaned
}

Write-Host "All language files complete!"
